plugins {
    id 'com.android.application'
}

android {
    namespace 'com.techgeekph.chatsupport'
    compileSdk 35

    defaultConfig {
        applicationId 'com.techgeekph.chatsupport'
        minSdk 23
        targetSdk 34
        versionCode 101
        versionName '1.0.1'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
